from enum import Enum


class Protocol(Enum):
    CMD_CLOSE_ALL_CLIENT = 0

    FO_SAVE_FILE = 100
    FO_DELETE_FILE = 101
    FO_OPEN_SAVE_PATH = 102
    FO_STROAGE_FILE = 103
    FO_SAVE_FILE_ADD_INFO = 104
    FO_NO_CONNECT = 105


    UI_SAVE_SUCCESS = 200
    UI_DELETE_SUCCESS = 201
    UI_STROAGE_SUCCESS = 202
    UI_SAVE_ERROR = 203
    UI_DELETE_ERROR = 204
    UI_STROAGE_ERROR = 205


